FROM shichenxie/dstudio:0.1.1


# java -------------------------------------------------------------------#
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    default-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
    
    
# packages ---------------------------------------------------------------#
# py
RUN conda install --quiet --yes \
    'JayDeBeApi' \
    'psycopg2' \ 
    'xgboost' \
    'sklearn2pmml' && \
    conda clean --all -f -y
  
# R
RUN conda install --quiet --yes \
    'r-rJava' \
    'r-odbc' \
    'r-RJDBC' \
    'r-RPostgres*' \ 
    'r-scorecard' \
    'r-xgboost' && \
    conda clean --all -f -y && \
    fix-permissions "${CONDA_DIR}"
    

# setting ----------------------------------------------------------------#
# RUN useradd -m -g users -G ds -d /home/test test



# docker build -t shichenxie/dstudio:sc -f Dockerfile_sc .
# mkdir -p $HOME/docker/dstudio_home/dstudio
# docker run -d -p 8888:8888 -v $HOME/docker/dstudio_home:/home --restart always --name dstudio_sc shichenxie/dstudio:sc

# secure-cookie-key for multiple uers in rstudio server
# docker exec -it dstudio bash
# chmod -R 777 /tmp/rstudio-server/secure-cookie-key

# save/load docker tar file
# docker save dstudio > dstudio.tar
# docker load --input dstudio.tar

# Authorization Area
# http://localhost:8888/hub/authorize
# http://localhost:8888/hub/change-password

# setting R environment config
# https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/
# Sys.getenv('SPARK_HOME')
# usethis::edit_r_environ() 
# Sys.getenv('R_HOME') # /usr/local/lib/R
# R_HOME/etc/.Renviron
