FROM jupyter/datascience-notebook:hub-1.2.2

WORKDIR /
USER root
# set local source.list
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
COPY ./linux_source/sources_ubuntu.list /etc/apt/sources.list

# java rstudio server ------------------ 
# 1.2.5042 # 1.3.959 # 1.4.1103
ARG RSTUDIO_VERSION=1.3.959
RUN apt-get update && \
    apt-get install -y \
        default-jdk \
        gdebi-core && \
    wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb -O /tmp/rstudio.deb && \
    gdebi --non-interactive /tmp/rstudio.deb && \
    rm /tmp/rstudio.deb && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
    
ENV PATH=/usr/lib/rstudio-server/bin:$PATH

# install shiny server ------------------
# https://github.com/rocker-org/shiny
RUN wget --no-verbose https://download3.rstudio.org/ubuntu-14.04/x86_64/VERSION -O "version.txt" && \
    VERSION=$(cat version.txt)  && \
    wget --no-verbose "https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-$VERSION-amd64.deb" -O ss-latest.deb && \
    gdebi -n ss-latest.deb && \
    rm -f version.txt ss-latest.deb && \
    . /etc/environment && \
    cp -R /opt/conda/lib/R/library/shiny/examples/* /srv/shiny-server/ && \
    chown $NB_UID:$NB_UID /srv/shiny-server/ && \
    chown shiny:shiny /var/lib/shiny-server 

COPY ./shiny/shiny-server.sh /usr/bin/shiny-server.sh
CMD ["/usr/bin/shiny-server.sh"]

# pkgs ------------------
# jupyter-rsession-proxy
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir \
    jupyter-rsession-proxy
# jupyter-shiny-proxy
ADD ./shiny/jupyter_shiny_proxy /tmp/jupyter_shiny_proxy
RUN pip install /tmp/jupyter_shiny_proxy && \
    rm -rf /tmp/*
    
# r pkgs # r-py # shiny
ARG CRAN_URL=https://mirrors.tuna.tsinghua.edu.cn/CRAN
RUN R --quiet -e "install.packages(c('png', 'reticulate'), repos='${CRAN_URL}')"  && \ 
    R --quiet -e "install.packages(c('shinythemes', 'shinydashboard'), repos='${CRAN_URL}')" && \ 
    rm -rf /tmp/* && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
    
# startup ------------------
# R startup # https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/
RUN echo 'options(repos = c(CRAN = "https://cran.rstudio.com/", CRANextra = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))' >> /opt/conda/lib/R/etc/Rprofile.site && \
    echo 'options(download.file.method = "curl")' >> /opt/conda/lib/R/etc/Rprofile.site && \
    echo 'RETICULATE_PYTHON = "/opt/conda/bin/python"' >> /opt/conda/lib/R/etc/Renviron.site
# R_HOME, R_LIBS, LD_LIBRARY_PATH, PATH

# rstudio server config
RUN echo 'session-default-working-dir=/home/jovyan/work' >> /etc/rstudio/rsession.conf && \
    echo 'session-default-new-project-dir=/home/jovyan/work' >> /etc/rstudio/rsession.conf
COPY ./config/rstudio-prefs.json /etc/rstudio/rstudio-prefs.json


RUN mkdir -p /home/jovyan/share && \
    ln -s /home/jovyan/share /home/jovyan/work/share
    
WORKDIR $HOME
USER $NB_UID

# docker build -t shichenxie/dstudio_lab:ds -f Dockerfile_labds .

# fix openssl issue # https://github.com/tschaffter/rstudio/issues/1
# RUN conda remove --force -y openssl
