FROM jupyter/datascience-notebook:hub-1.3.0

WORKDIR /
USER root
# set local source.list
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
COPY ./linux_source/sources_ubuntu.list /etc/apt/sources.list

# java pandoc ------------------
RUN apt-get update && \
    apt-get install -y default-jdk pandoc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# rstudio server / shiny ------------------ 
COPY scripts /rocker_scripts

ENV R_HOME=/opt/conda/lib/R
ENV R_LIB=/opt/conda/lib/R/library
ENV CRAN=https://packagemanager.rstudio.com/all/__linux__/focal/latest
ARG CRAN_URL=https://mirrors.tuna.tsinghua.edu.cn/CRAN

ENV TERM=xterm
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TZ=Etc/UTC

ENV R_VERSION=4.0.3
ENV S6_VERSION=v2.1.0.2
ENV RSTUDIO_VERSION=1.4.1106
ENV PANDOC_VERSION=default

ENV PATH=/usr/lib/rstudio-server/bin:$PATH
RUN /rocker_scripts/install_rstudio.sh && \
    /rocker_scripts/install_pandoc.sh && \
    /rocker_scripts/install_shiny_server.sh && \
    ## folder permission
    chown $NB_UID:$NB_UID /srv/shiny-server/ && \
    chown $NB_UID:$NB_UID /var/lib/shiny-server && \
    chown $NB_UID:$NB_UID /var/log/shiny-server && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# pkgs ------------------
# py pgks
ENV RSESSION_PROXY_RSTUDIO_1_4=yes
ADD ./pkgs-jupyter-rstudioshiny  /tmp
RUN python3 -m pip install /tmp/jupyter-rsession-proxy && \ 
    python3 -m pip install /tmp/jupyter_shiny_proxy && \ 
    python3 -m pip install datatable && \ 
    rm -rf /tmp/* && \
    ## conda install
    conda install --quiet --yes 'JayDeBeApi' && \
    conda clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# r pkgs 
RUN conda install --quiet --yes \
        'r-png' 'r-reticulate' \
        'r-odbc' 'r-rjdbc' 'r-rpostgres' \
        'r-mlr3' 'r-scorecard' && \
    conda clean --all -f -y && \
    ## R install.packages
    ## R --quiet -e "install.packages(c('mlr3', 'scorecard'), repos='${CRAN_URL}')"  && \ 
    rm -rf /tmp/* && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
    

# startup ------------------
# R startup # https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/
RUN echo 'options(repos = c(CRAN = "https://cran.rstudio.com/", CRANextra = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))' >> /opt/conda/lib/R/etc/Rprofile.site && \
    echo 'RETICULATE_PYTHON = "/opt/conda/bin/python"' >> /opt/conda/lib/R/etc/Renviron.site
# R_HOME, R_LIBS, LD_LIBRARY_PATH, PATH

# rstudio server config
RUN echo 'session-default-working-dir=/home/jovyan/work' >> /etc/rstudio/rsession.conf && \
    echo 'session-default-new-project-dir=/home/jovyan/work' >> /etc/rstudio/rsession.conf
COPY ./config/rstudio-prefs.json /etc/rstudio/rstudio-prefs.json


RUN mkdir -p /home/jovyan/share && \
    ln -s /home/jovyan/share /home/jovyan/work/share
    
WORKDIR $HOME
USER $NB_UID

# docker build -t shichenxie/dstudio_lab:ds1.3.0 -f Dockerfile_labds_jupyter .

# fix openssl issue # https://github.com/tschaffter/rstudio/issues/1
# RUN conda remove --force -y openssl
