FROM shichenxie/dstudio_lab:ds

WORKDIR /
USER root
# java 
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    default-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
    

USER $NB_UID
# r/py packages 
RUN conda install --quiet --yes \
    'JayDeBeApi' \
    'psycopg2' \ 
    'xgboost' \
    'sklearn2pmml' \
    'r-rJava' \
    'r-odbc' \
    'r-RJDBC' \
    'r-RPostgres*' \ 
    'r-scorecard' \
    'r-xgboost' && \
    conda clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"


# jupyter config 
# COPY ./config/jupyter_notebook_config.py $HOME/.jupyter/jupyter_notebook_config.py 

WORKDIR $HOME

# docker build -t shichenxie/dstudio_lab:sc -f Dockerfile_labsc .