FROM jupyter/r-notebook:hub-4.0.2
# docker pull jupyter/datascience-notebook:hub-4.0.2 --platform linux/amd64
# docker pull jupyter/r-notebook:hub-4.0.2 --platform linux/amd64

# https://hub.docker.com/r/jupyter/datascience-notebook/
# https://github.com/rocker-org/rocker-versioned2
# https://www.docker.com/blog/user-guided-caching-in-docker-for-mac/


USER root
WORKDIR /

# rstudio server ------------------ 
# ENV CONDA_DIR=/opt/conda
ENV R_HOME=/opt/conda/lib/R
ENV R_LIB=/opt/conda/lib/R/library
ENV CRAN=https://packagemanager.rstudio.com/all/__linux__/focal/latest
ARG CRAN_URL=https://mirrors.tuna.tsinghua.edu.cn/CRAN/

ENV S6_VERSION=v2.1.0.2
ENV RSTUDIO_VERSION=2023.12.0+369
ENV DEFAULT_USER=${NB_USER}
ENV PANDOC_VERSION=default
ENV PATH=/usr/lib/rstudio-server/bin:$PATH

COPY scripts /rocker_scripts
# RUN awk '/^DEFAULT_USER=/ { $0 = "#" $0 }; 1' /rocker_scripts/install_rstudio.sh > /rocker_scripts/install_rstudio.sh 
# install_shiny_server: # install2.r  # cp -R $R_LIB/shiny/examples/* /srv/shiny-server/

RUN /rocker_scripts/install_rstudio.sh && \
    apt-get update && \
    apt-get install -y qpdf cron default-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*  && \
    rm -rf /tmp/* && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# pkgs ------------------
# python3 -m pip install --upgrade https://github.com/jupyterhub/jupyter-rsession-proxy/tarball/master &&\
## conda install # 
# conda install --quiet --yes pip && \    
RUN conda install --quiet --yes 'r-png' 'r-odbc' 'r-RJDBC' 'r-RPostgres' 'r-protolite' && \
    conda clean --all -f -y && \ 
    rm -rf /tmp/* && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

## pip install # -i https://pypi.tuna.tsinghua.edu.cn/simple 
ENV RSESSION_PROXY_RSTUDIO_1_4=yes
RUN python3 -m pip install --no-cache jupyter-rsession-proxy 

## CRAN install 
## r-dbi https://github.com/r-dbi # service cron start ## 'RMySQL', 
COPY echarts4r.maps-master.zip /tmp/echarts4r.maps-master.zip 
RUN R --quiet -e "install.packages(c('RClickhouse', \
        'reticulate', 'blastula', 'rjson', 'data.tree', 'RProtoBuf', 'cronR', \
        'blogdown', 'showtext', 'tidytext', 'stringdist', 'jiebaR',  \
        'echarts4r', 'plotly', 'visNetwork', 'qgraph', 'ggExtra', \ 
        'xgboost', 'mlr3', 'scorecard', 'xefun', \
        'tsibble', 'fable', 'pedquant', 'webdriver'), repos='${CRAN_URL}'); \
        devtools::install_local('/tmp/echarts4r.maps-master.zip')"  && \ 
    rm -rf /tmp/* && \ 
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN R --quiet -e "install.packages(c('h2o'), repos='${CRAN_URL}')" && \ 
    rm -rf /tmp/* && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# setting for service cron start
RUN chmod gu+rw /var/run/ && \
    chmod gu+s  /usr/sbin/cron

# shiny ------------------
RUN /rocker_scripts/install_shiny_server.sh && \
    chown -R $NB_UID:$NB_UID /srv/shiny-server/ && \
    chown -R $NB_UID:$NB_UID /var/lib/shiny-server && \
    chown -R $NB_UID:$NB_UID /var/log/shiny-server && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN python3 -m pip install --no-cache jupyter-shiny-proxy && \
    R --quiet -e "install.packages(c( \
        'golem', 'shinipsum', 'fakir', 'gemstones', 'attachment', \
        'flexdashboard', 'bs4Dash', 'shinydashboard', 'shinydashboardPlus', \
        'shinyFeedback', 'shinyWidgets', 'kableExtra', 'DT', \
        'bslib', 'sass', 'thematic', 'htmltools', 'jquerylib', 'htmlwidgets', \
        'shinythemes', 'shinycssloaders', 'shinyBS', 'shiny.i18n', 'shinyFiles', 'miniUI', \
         'sparkline', 'incidence', 'EpiEstim'), repos='${CRAN_URL}')"  && \ 
    rm -rf /tmp/* && \
    fix-permissions "${R_HOME}" && \
    fix-permissions "/home/${NB_USER}" 

# setting jupyter_shiny_proxy home directory to /srv/shiny-server
RUN cd /opt/conda/lib/python3.11/site-packages/jupyter_shiny_proxy &&  \
    awk '{sub(/os.getcwd\(\)/,"\"/srv/shiny-server\"")}1' __init__.py > /tmp/temp.py && mv /tmp/temp.py __init__.py && \ 
    cd /

# startup ------------------
# R startup # https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/
RUN echo 'options(repos = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/", CRANextra = "https://cran.rstudio.com/"))' >> /opt/conda/lib/R/etc/Rprofile.site && \
    echo 'RETICULATE_PYTHON = "/opt/conda/bin/python"' >> /opt/conda/lib/R/etc/Renviron.site
# R_HOME, R_LIBS, LD_LIBRARY_PATH, PATH

# rstudio server config
RUN echo 'session-default-working-dir=/home/jovyan/work' >> /etc/rstudio/rsession.conf && \
    echo 'session-default-new-project-dir=/home/jovyan/work' >> /etc/rstudio/rsession.conf
COPY ./config/rstudio-prefs.json /home/${NB_USER}/.config/rstudio/rstudio-prefs.json

# jupyterlab config
COPY ./config/overrides.json /opt/conda/share/jupyter/lab/settings/


RUN mkdir -p /home/jovyan/share && \
    ln -s /home/jovyan/share /home/jovyan/work/share && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# set localtime
RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

WORKDIR $HOME
USER $NB_UID

# docker build --platform linux/amd64 -t shichenxie/dstudio_lab:4.0r -f ./Dockerfile_4.0r .
# docker build --progress=plain --no-cache  --platform linux/amd64 -t shichenxie/dstudio_lab:4.0r -f ./Dockerfile_jupyter4.0_rstudio .


# fix openssl issue # https://github.com/tschaffter/rstudio/issues/1
# RUN conda remove --force -y openssl
