# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#
name: Test

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.rst"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.rst"
      - ".github/workflows/*"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
  workflow_dispatch:

jobs:
  pytest:
    name: Run pytests
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.6"
            jupyterhub-version: "1.3.*"
          - python-version: "3.7"
            jupyterhub-version: "1.4.*"
          - python-version: "3.8"
            jupyterhub-version: "1.*"
          - python-version: "3.9"
            jupyterhub-version: "2.*"
          - python-version: "3.10"
            jupyterhub-version: "2.*"
          - python-version: "3.11.0-rc.1"
            jupyterhub-version: "3.*"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Python dependencies
        run: |
          pip install --no-cache-dir -r dev-requirements.txt
          pip install --pre "jupyterhub==${{ matrix.jupyterhub-version }}"
          pip install .

      - name: Run tests
        continue-on-error: ${{ matrix.accept-failure == true }}
        run: |
          pytest --verbose --maxfail=2 --color=yes

      - name: Upload code coverage report
        run: codecov
