FROM rocker/verse:4.0.3

# set local source.list
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
COPY ./linux_source/sources_debian.list /etc/apt/sources.list

# install anaconda3 ------------------
# https://hub.docker.com/r/continuumio/anaconda3/dockerfile
ENV LANG=C.UTF-8 
ENV LC_ALL=C.UTF-8 
ENV PATH=/opt/conda/bin:$PATH 
ENV CONDA_DIR=/opt/conda

RUN wget --quiet https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-2020.11-Linux-x86_64.sh  -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
    /opt/conda/bin/conda clean -afy

CMD [ "/bin/bash" ]

# pkgs ------------------
# py pgks
ENV RSESSION_PROXY_RSTUDIO_1_4=yes
ADD ./pkgs-jupyter-rstudioshiny  /tmp
RUN python3 -m pip install \
        /tmp/jupyter-rsession-proxy \
        /tmp/jupyter_shiny_proxy \
        datatable \
        jupyterhub==1.2.2 && \ 
    rm -rf /tmp/* && \
    ## conda install
    conda install --quiet --yes 'JayDeBeApi' && \
    conda clean --all -f -y 

# r pkgs 
ARG CRAN_URL=https://mirrors.tuna.tsinghua.edu.cn/CRAN
RUN R --quiet -e "install.packages(c('png', 'reticulate', 'IRkernel'), repos='${CRAN_URL}')"  && \ 
    rm -rf /tmp/* 

RUN conda install --quiet --yes 'jupyterlab' && \
    conda clean --all -f -y 

# startup ------------------
# R startup # https://rviews.rstudio.com/2017/04/19/r-for-enterprise-understanding-r-s-startup/
RUN echo 'options(repos = c(CRAN = "https://cran.rstudio.com/", CRANextra = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))' >> /etc/R/Rprofile.site &&\
    echo 'RETICULATE_PYTHON = "/opt/conda/bin/python"' >> /etc/R/Renviron.site
# R_HOME, R_LIBS, LD_LIBRARY_PATH, PATH

# rstudio server config
RUN R --quiet -e "IRkernel::installspec(user = FALSE)" && \
    echo 'session-default-working-dir=/home/jovyan/work' >> /etc/rstudio/rsession.conf && \
    echo 'session-default-new-project-dir=/home/jovyan/work' >> /etc/rstudio/rsession.conf
COPY ./config/rstudio-prefs.json /etc/rstudio/rstudio-prefs.json


ENV USER=jovyan
ENV USERID=200
RUN useradd -m $USER -u $USERID && \
    mkdir -p /home/$USER && \
    chown -R $USER /home/$USER && \
    mkdir -p /home/jovyan/work && \
    mkdir -p /home/jovyan/share && \
    ln -s /home/jovyan/share /home/jovyan/work/share
    
WORKDIR $HOME
USER $USERID

# docker build -t shichenxie/dstudio_lab:ds2 -f Dockerfile_labds_rocker .

# fix openssl issue # https://github.com/tschaffter/rstudio/issues/1
# RUN conda remove --force -y openssl
